# Definition: CollisionSettingsDefinition
# Hash: 3d66fca6
# SNOFileHeader.dwFormatHash: 2005626
# Flags: 00000000 00000000 00000000 00000000

0x8: tCollFlags # ActorCollisionFlags
0x10: unk_a882afd # DT_INT (1 bits used)
0x14: unk_54403ff # DT_INT (1 bits used)
0x18: null or eof # DT_NULL
