# Definition: Environment
# Hash: 99435235
# Flags: 0x30a

0x0: tPostFXParams # PostFXParams
0x20: snoSkyboxActor # DT_SNO (32 bits used) {group 0x1 "Actor"}
0x24: snoAudioContext # DT_SNO (32 bits used) {group 0x5d "AudioContext"}
0x28: snoWeather # DT_SNO (32 bits used) {group 0x2f "Weather"}
0x2c: snoSkylightTex # DT_SNO (32 bits used) {group 0x2c "Texture"}
0x30: unk_afd6821 # bcQuat
0x40: snoOceanMaterial # DT_SNO (32 bits used) {group 0x39 "Material"}
0x44: snoGroundFogMaterial # DT_SNO (32 bits used) {group 0x39 "Material"}
0x48: flFarPlaneCap # DT_FLOAT (32 bits used)
0x4c: snoOceanAmbient # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x50: unk_31e7772 # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x54: snoRiverAmbient # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x58: snoStreamAmbient # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x5c: snoCliffEdgeAmbient # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x60: unk_f4f9d6f # DT_INT (1 bits used)
0x64: unk_55eead1 # DT_FLOAT (32 bits used)
0x68: unk_a7ebd97 # DT_INT (1 bits used)
0x6c: null or eof # DT_NULL
