# Definition: MaterialVectorValuesUsed
# Hash: f58f01c3
# Flags: 0x30a

0x0: snoMaterialValue # DT_SNO (32 bits used) {group 0x51 "MaterialValue"}
0x4: vDefaultValue # DT_VECTOR4D
0x14: null or eof # DT_NULL
