# Definition: RunTimeMaterialValues
# Hash: 4d7ce083
# Flags: 00000000 00000000 00000011 00011010

0x0: arMaterialScalarValues # DT_VARIABLEARRAY => RunTimeMaterialScalarValueEntry
0x10: arMaterialScalarGraphs # DT_VARIABLEARRAY => RunTimeMaterialScalarGraphEntry
0x20: arMaterialVectorValues # DT_VARIABLEARRAY => RunTimeMaterialVectorValueEntry
0x30: arMaterialVectorGraphs # DT_VARIABLEARRAY => RunTimeMaterialVectorGraphEntry
0x40: null or eof # DT_NULL
