# Definition: UIDateTimeSettings
# Hash: b2d29bdc
# Flags: 0x302

0x0: unk_a8652e7 # DT_INT64 (64 bits used)
0x8: unk_e037d99 # DT_ENUM (32 bits used)
0xc: unk_cc3458a # DT_ENUM (32 bits used)
0x10: eStyle # DT_ENUM (32 bits used)
0x18: null or eof # DT_NULL
