# Definition: VolumetricCloudSettingsOptionalFieldMapDefaults
# Hash: f49e9532
# Flags: 0x300

0x0: bEnabled # DT_INT (1 bits used)
0x4: unk_f14ffed # DT_VECTOR3D
0x10: pathExtinction # InterpolationPath_float
0x48: unk_169823a # InterpolationPath_float
0x80: flCloudIntensity # DT_FLOAT (32 bits used)
0x88: unk_beb976c # InterpolationPath_float
0xc0: pathCoverageBias # InterpolationPath_float
0xf8: pathCloudTypeBias # InterpolationPath_float
0x130: unk_d14bc79 # DT_FLOAT (32 bits used)
0x134: unk_f852d87 # DT_FLOAT (32 bits used)
0x138: unk_86d2585 # DT_FLOAT (32 bits used)
0x13c: vecWeatherDataOffset # DT_VECTOR2D
0x144: unk_67b3c4a # DT_FLOAT (32 bits used)
0x148: flCirrusCloudIntensity # DT_FLOAT (32 bits used)
0x14c: vecCirrusOffset # DT_VECTOR2D
0x158: unk_95e2b10 # InterpolationPath_float
0x190: unk_b9a067e # InterpolationPath_float
0x1c8: unk_2f13301 # InterpolationPath_float
0x200: unk_caea994 # DT_FLOAT (32 bits used)
0x204: unk_e4f6034 # DT_FLOAT (32 bits used)
0x208: pathTurbulenceStrength # InterpolationPath_float
0x240: vCloudWind # DT_VECTOR3D
0x250: unk_ab0e39e # InterpolationPath_float
0x288: flCloudShellInnerRadius # DT_FLOAT (32 bits used)
0x28c: flCloudShellThickness # DT_FLOAT (32 bits used)
0x290: flCloudStartingHeight # DT_FLOAT (32 bits used)
0x294: bOverrideGlobalWind # DT_INT (1 bits used)
0x298: vecWindDirectionOverride # DT_VECTOR3D
0x2a4: flWindIntensityScale # DT_FLOAT (32 bits used)
0x2a8: snoTexWeatherData # DT_SNO (32 bits used) {group 0x2c "Texture"}
0x2ac: snoTexCirrus # DT_SNO (32 bits used) {group 0x2c "Texture"}
0x2b0: null or eof # DT_NULL
